### ISSUE TITLE
Fix to solution: TypeErrorr in actor_critic tensorflow2 main.py

### ISSUE THREAD

**Issue by simoneliasen** [philtabor/Youtube-Code-Repository#37]
In the following document:
Youtube-Code-Repository/ReinforcementLearning/PolicyGradient/actor_critic/tensorflow2/main.py 

Running the program returns:
File "actor_critic.py", line 157, in <module>
    agent.learn(observation, action, reward, observation_, done)
TypeError: learn() takes 5 positional arguments but 6 were given

I think this could be fixed by changing the following line:
agent.learn(observation, action, reward, observation_, done) 

to:
agent.learn(observation, reward, observation_, done)

Sorry for the suggestion format, first time suggesting fixes :D

**Comment by philtabor** [comment]
Yes, this is correct. I fixed this in a recent commit. Thanks!
