### ISSUE TITLE
Epsilon = 0 on main_keras_dqn_lunar_lander.py

### ISSUE THREAD

**Issue by renatoviolin** [philtabor/Youtube-Code-Repository#7]
Hi Phil,
In Agent constructor the epsilon=0. Wouldn't be epsilon = 1?

Thanks
Renato

**Comment by philtabor** [comment]
Hey Renato, this is because I set it to 0 for making YouTube videos, since I want to load a fully trained agent and generate videos of the agent landing on the pad. 

When you are training, it should indeed be set to 1, and you should comment out the agent.load_model() on line 13.
